name: OPA Policy Check

on:
  push:
    branches:
      - main

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Validate Policy
        run: |
          opa eval \
          --data policy.rego \
          --input input.json \
          "data.cicd.deny"